###
# Get all entries
GET http://localhost:3001/api/blogs

###
# Get entry
GET http://localhost:3001/api/blogs/60322ab521a62f441da313f8

###
# Delete entry
DELETE http://localhost:3001/api/blogs/60321ab95eabcc304d20b60c

###
# Add entry
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Full Stack Tutorial",
    "author": "LeBron James",
    "url": "fullstacklebron.com/blogs/fullstacktut",
    "likes": 100
}

###
# Update entry
PUT http://localhost:3001/api/blogs/60321ab95eabcc304d20b60c
Content-Type: application/json

{
    "likes": 300
}