### Get all
GET http://localhost:3001/api/blogs

### Get single
GET http://localhost:3001/api/blogs/60322ab521a62f441da313f8

### Delete
DELETE http://localhost:3001/api/blogs/60369fa1fe228081ff1df481
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MDM3NjA2MzkzMDNlZjE5NTRlYWI5YTQiLCJpYXQiOjE2MTQyNDE5MDV9.lw2Ws4LEQSrtP70420TbJgx7pq4BBTyBTYkB9FhQxQE

### Create
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJiOCIsImlkIjoiNjAzNjU5ZWU5M2U5YmIzZDA5ZjUyYTM5IiwiaWF0IjoxNjE0MTkyMTgzfQ.eX4316ByUT2SihHN8D7WS1jIDzXBHPucwtu1SgEAQhE

{
    "title": "Test Title 1",
    "author": "Test Author 1",
    "url": "test.com",
    "likes": 10
}

### Update
PUT http://localhost:3001/api/blogs/60321ab95eabcc304d20b60c
Content-Type: application/json

{
    "likes": 300
}